### PR TITLE
Use constructor injection instead of field injection

### PR DESCRIPTION
**Pull request by eximius313**
PR for: https://github.com/innoveit/play2-pdf/issues/32
It's for 1.8.0 version because I need it now.
It can be easily changed for 1.9.0

### CODE REVIEW

**Comment by eximius313** [comment]
@marcosinigaglia sorry, I don't know how to set `1.8.1` correctly...

**Comment by marcosinigaglia** [comment]
Hi @eximius313 , can you make a PR in a new branch? I don't know if is it possible, alternatively I create a new branch for 1.8.0.

**Comment by eximius313** [comment]
Please create 1.8 branch (from 1.8.0 tag) and I'll provide second PR

**Comment by eximius313** [comment]
@marcosinigaglia - Done: https://github.com/innoveit/play2-pdf/pull/34

**Pull request closed without merging**
